import type { Signal, MonitoredUrl } from '@/types';

export const sampleSignals: Signal[] = [
  {
    id: '1',
    category: 'deadline',
    categoryName: 'Deadline Change',
    importance: 'high',
    importanceLabel: 'HIGH',
    site: 'stanford.edu/admissions',
    url_id: '1',
    time: '12m ago',
    detected_at: new Date(Date.now() - 12 * 60000).toISOString(),
    title: 'Application deadline moved to Feb 15',
    summary: 'Regular decision deadline shifted from March 1 to February 15 — two weeks earlier than previously posted.',
    why_it_matters: 'You have significantly less time to prepare. Prioritize completing your application immediately.',
    evidence: [
      { label: 'Before', value: 'March 1' },
      { label: 'After', value: 'Feb 15' }
    ],
    read: false,
  },
  {
    id: '2',
    category: 'pricing',
    categoryName: 'Pricing',
    importance: 'high',
    importanceLabel: 'HIGH',
    site: 'vercel.com/pricing',
    url_id: '2',
    time: '1h ago',
    detected_at: new Date(Date.now() - 60 * 60000).toISOString(),
    title: 'Pro plan increased from $20 to $25',
    summary: 'Vercel raised Pro tier pricing by 25% and introduced a new Enterprise tier with custom pricing.',
    why_it_matters: 'If you are on Pro, your costs will increase. Evaluate whether Enterprise features justify the upgrade.',
    evidence: [
      { label: 'Pro', value: '$20 → $25' },
      { label: 'Enterprise', value: 'New tier' }
    ],
    read: false,
  },
  {
    id: '3',
    category: 'content',
    categoryName: 'New Content',
    importance: 'med',
    importanceLabel: 'MED',
    site: 'devpost.com/hackathons',
    url_id: '3',
    time: '3h ago',
    detected_at: new Date(Date.now() - 3 * 60 * 60000).toISOString(),
    title: '3 new hackathons posted',
    summary: 'Devpost added Spring 2026 hackathons including an AI/ML competition with $50K in prizes and a climate tech challenge.',
    why_it_matters: 'New opportunities to build, learn, and win prizes. Deadlines approaching in 4-6 weeks.',
    evidence: [
      { label: 'Added', value: 'AI/ML Hackathon' },
      { label: 'Added', value: 'Climate Tech Challenge' },
      { label: 'Added', value: 'Student Design Jam' }
    ],
    read: false,
  },
  {
    id: '4',
    category: 'feature',
    categoryName: 'New Feature',
    importance: 'med',
    importanceLabel: 'MED',
    site: 'notion.so/changelog',
    url_id: '4',
    time: '5h ago',
    detected_at: new Date(Date.now() - 5 * 60 * 60000).toISOString(),
    title: 'AI Q&A + Database Automations released',
    summary: 'Notion launched two major features: AI-powered workspace Q&A and automated database workflows.',
    why_it_matters: 'Automation could streamline your workflows. AI Q&A changes how you search workspace knowledge.',
    evidence: [],
    read: false,
  },
  {
    id: '5',
    category: 'policy',
    categoryName: 'Policy Update',
    importance: 'high',
    importanceLabel: 'HIGH',
    site: 'sec.gov/rules',
    url_id: '5',
    time: '1d ago',
    detected_at: new Date(Date.now() - 24 * 60 * 60000).toISOString(),
    title: 'New cybersecurity disclosure requirements',
    summary: 'SEC published updated rules requiring companies to report material cybersecurity incidents within 4 business days.',
    why_it_matters: 'If you invest or work in compliance, this significantly changes reporting expectations and timelines.',
    evidence: [
      { label: 'Reporting window', value: 'Previously undisclosed' },
      { label: 'New requirement', value: '4 business days' }
    ],
    read: true,
  },
  {
    id: '6',
    category: 'announce',
    categoryName: 'Announcement',
    importance: 'low',
    importanceLabel: 'LOW',
    site: 'github.blog',
    url_id: '6',
    time: '2d ago',
    detected_at: new Date(Date.now() - 48 * 60 * 60000).toISOString(),
    title: 'GitHub Copilot X roadmap updated',
    summary: 'GitHub shared updated roadmap for Copilot including voice-to-code, pull request summaries, and CLI integration.',
    why_it_matters: 'Interesting if you use GitHub daily. Voice-to-code could fundamentally change how you code.',
    evidence: [],
    read: true,
  },
  {
    id: '7',
    category: 'content',
    categoryName: 'New Content',
    importance: 'med',
    importanceLabel: 'MED',
    site: 'coursera.org/browse',
    url_id: '7',
    time: '3d ago',
    detected_at: new Date(Date.now() - 72 * 60 * 60000).toISOString(),
    title: '12 new courses in Generative AI',
    summary: 'Coursera added courses on LLMs, prompt engineering, diffusion models, and AI ethics from Stanford and DeepLearning.AI.',
    why_it_matters: 'Upskilling opportunities if you are building or working with generative AI systems.',
    evidence: [
      { label: 'New courses', value: '12 added' },
      { label: 'Partners', value: 'Stanford, DeepLearning.AI' }
    ],
    read: true,
  },
  {
    id: '8',
    category: 'pricing',
    categoryName: 'Pricing',
    importance: 'low',
    importanceLabel: 'LOW',
    site: 'stripe.com/billing',
    url_id: '8',
    time: '4d ago',
    detected_at: new Date(Date.now() - 96 * 60 * 60000).toISOString(),
    title: 'Volume-based discounts introduced',
    summary: 'Stripe Billing now offers tiered pricing for high-volume users, with discounts starting at 100K transactions/month.',
    why_it_matters: 'Potential cost savings if your usage crosses volume thresholds. Worth checking against your current bill.',
    evidence: [],
    read: true,
  },
];

export const sampleWatchlist: MonitoredUrl[] = [
  {
    id: '1',
    user_id: 'demo',
    name: 'Stanford Admissions',
    url: 'https://admissions.stanford.edu',
    category: 'Education',
    scan_frequency: 'daily',
    status: 'watching',
    last_scan: new Date(Date.now() - 12 * 60000).toISOString(),
    last_signal_at: new Date(Date.now() - 12 * 60000).toISOString(),
    signal_count: 2,
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60000).toISOString(),
    is_active: true,
    noise_sensitivity: 'balanced',
  },
  {
    id: '2',
    user_id: 'demo',
    name: 'Vercel',
    url: 'https://vercel.com/pricing',
    category: 'Technology',
    scan_frequency: 'daily',
    status: 'watching',
    last_scan: new Date(Date.now() - 60 * 60000).toISOString(),
    last_signal_at: new Date(Date.now() - 60 * 60000).toISOString(),
    signal_count: 1,
    created_at: new Date(Date.now() - 25 * 24 * 60 * 60000).toISOString(),
    is_active: true,
    noise_sensitivity: 'balanced',
  },
  {
    id: '3',
    user_id: 'demo',
    name: 'Devpost Hackathons',
    url: 'https://devpost.com/hackathons',
    category: 'Careers',
    scan_frequency: 'daily',
    status: 'watching',
    last_scan: new Date(Date.now() - 3 * 60 * 60000).toISOString(),
    last_signal_at: new Date(Date.now() - 3 * 60 * 60000).toISOString(),
    signal_count: 1,
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60000).toISOString(),
    is_active: true,
    noise_sensitivity: 'balanced',
  },
  {
    id: '4',
    user_id: 'demo',
    name: 'SEC Filings',
    url: 'https://sec.gov/rules',
    category: 'Research',
    scan_frequency: 'daily',
    status: 'watching',
    last_scan: new Date(Date.now() - 24 * 60 * 60000).toISOString(),
    last_signal_at: new Date(Date.now() - 24 * 60 * 60000).toISOString(),
    signal_count: 1,
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60000).toISOString(),
    is_active: true,
    noise_sensitivity: 'conservative',
  },
  {
    id: '5',
    user_id: 'demo',
    name: 'Coursera Browse',
    url: 'https://coursera.org/browse',
    category: 'Education',
    scan_frequency: 'weekly',
    status: 'watching',
    last_scan: new Date(Date.now() - 72 * 60 * 60000).toISOString(),
    last_signal_at: new Date(Date.now() - 72 * 60 * 60000).toISOString(),
    signal_count: 1,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60000).toISOString(),
    is_active: true,
    noise_sensitivity: 'balanced',
  },
];
